### ISSUE TITLE
Ban fails due to cant get map img

### ISSUE THREAD

**Issue by M203** [Roxedus/lsio-docker-mods#1]
Running lsio letsencrypt via dockstarter on a raspberry pi. 

Added docker mod via dockstarter overrides file as per below. 
```
version: "3.4"  # this must match the version in docker-compose.yml
services:
  netdata:
    image:           netdata/netdata:latest-armhf
  letsencrypt:
    environment:
    - DOCKER_MODS=roxedus/lsio-docker-mods:le-discord_f2b-latest
    - DISC_HOOK=MYDISCHOOK
    - DISC_ME=MYUSERID
    - DISC_API=MYCONSUMERKEYFROMMAPQUEST
```

Log from portainer (it had already run once, fail2ban.py, geo db etc has been downloaded)

> [mod-init] Attempting to run Docker Modification Logic
> 
> 
> [mod-init] Applying roxedus/lsio-docker-mods:le-discord_f2b-latest files to container
> 
> 
> [mod-init] roxedus/lsio-docker-mods:le-discord_f2b-latest at sha256:5e5bf6af0168509095ee9a05a95a3950d51351cb1793b361cfda52c50bf02da5 has been previously applied skipping

After start I get the notifications in discord that the jails have started. However it stops there and there is no restore of ban. 

Checking fail2ban log it says this for every restore of ban. Redacted ip:s.

> 2020-05-15 10:03:43,895 fail2ban.actions        [428]: NOTICE  [nginx-botsearch] Restore Ban X.XX.255.136
> 2020-05-15 10:03:45,579 fail2ban.utils          [428]: #39-Lev. 764c0bd8 -- exec: python3 /config/fail2ban/Fail2Ban.py -a ban -j nginx-http-auth -i XXX.XXX.109.37 -t 24 -f 3
> 2020-05-15 10:03:45,580 fail2ban.utils          [428]: ERROR   764c0bd8 -- stderr: 'Traceback (most recent call last):'
> 2020-05-15 10:03:45,581 fail2ban.utils          [428]: ERROR   764c0bd8 -- stderr: '  File "/config/fail2ban/Fail2Ban.py", line 98, in <module>'
> 2020-05-15 10:03:45,581 fail2ban.utils          [428]: ERROR   764c0bd8 -- stderr: '    if (payload:= disc.create_payload()):'
> 2020-05-15 10:03:45,581 fail2ban.utils          [428]: ERROR   764c0bd8 -- stderr: '  File "/config/fail2ban/Fail2Ban.py", line 28, in create_payload'
> 2020-05-15 10:03:45,582 fail2ban.utils          [428]: ERROR   764c0bd8 -- stderr: '    webhook["embeds"][0]["image"] = {"url": f"{self.data[\'map-img\']}"}'
> 2020-05-15 10:03:45,582 fail2ban.utils          [428]: ERROR   764c0bd8 -- stderr: "KeyError: 'map-img'"
> 2020-05-15 10:03:45,582 fail2ban.utils          [428]: ERROR   764c0bd8 -- returned 1
> 2020-05-15 10:03:45,583 fail2ban.actions        [428]: ERROR   Failed to execute ban jail 'nginx-http-auth' action 'discordEmbed' info 'ActionInfo({'ip': 'XXX.XXX.109.37', 'fid': <function Actions.ActionInfo.<lambda> at 0x7684f9b8>, 'failures': 3, 'raw-ticket': <function Actions.ActionInfo.<lambda> at 0x7684fc88>})': Error banning XXX.XXX.109.37
> 2020-05-15 10:03:45,584 fail2ban.actions        [428]: NOTICE  [nginx-http-auth] Restore Ban XXX.XXX.109.52
> 2020-05-15 10:03:47,208 fail2ban.utils          [428]: #39-Lev. 764c0db8 -- exec: python3 /config/fail2ban/Fail2Ban.py -a ban -j nginx-botsearch -i 3.14.255.136 -t 24 -f 2
> 2020-05-15 10:03:47,209 fail2ban.utils          [428]: ERROR   764c0db8 -- stderr: 'Traceback (most recent call last):'
> 2020-05-15 10:03:47,209 fail2ban.utils          [428]: ERROR   764c0db8 -- stderr: '  File "/config/fail2ban/Fail2Ban.py", line 98, in <module>'
> 2020-05-15 10:03:47,210 fail2ban.utils          [428]: ERROR   764c0db8 -- stderr: '    if (payload:= disc.create_payload()):'
> 2020-05-15 10:03:47,210 fail2ban.utils          [428]: ERROR   764c0db8 -- stderr: '  File "/config/fail2ban/Fail2Ban.py", line 28, in create_payload'
> 2020-05-15 10:03:47,210 fail2ban.utils          [428]: ERROR   764c0db8 -- stderr: '    webhook["embeds"][0]["image"] = {"url": f"{self.data[\'map-img\']}"}'
> 2020-05-15 10:03:47,211 fail2ban.utils          [428]: ERROR   764c0db8 -- stderr: "KeyError: 'map-img'"
> 2020-05-15 10:03:47,211 fail2ban.utils          [428]: ERROR   764c0db8 -- returned 1
> 2020-05-15 10:03:47,212 fail2ban.actions        [428]: ERROR   Failed to execute ban jail 'nginx-botsearch' action 'discordEmbed' info 'ActionInfo({'ip': 'X.XX.255.136', 'fid': <function Actions.ActionInfo.<lambda> at 0x7684f9b8>, 'failures': 2, 'raw-ticket': <function Actions.ActionInfo.<lambda> at 0x7684fc88>})': Error banning X.XX.255.136

I cant really tell what I am doing wrong. I have tried two different consumer keys from Mapquest.

**Comment by Roxedus** [comment]
Is this a wan ip? Cant really tell without the actually useful parts of the ip.

**Comment by M203** [comment]
Some unredacted error messages. Those would be wan ip:s.

```
2020-05-15 10:03:40,653 fail2ban.actions        [428]: NOTICE  [nginx-botsearch] Restore Ban 218.80.229.142
2020-05-15 10:03:42,265 fail2ban.utils          [428]: #39-Lev. 764c0bd8 -- exec: python3 /config/fail2ban/Fail2Ban.py -a ban -j nginx-http-auth -i 172.247.109.34 -t 24 -f 4
2020-05-15 10:03:42,266 fail2ban.utils          [428]: ERROR   764c0bd8 -- stderr: 'Traceback (most recent call last):'
2020-05-15 10:03:42,267 fail2ban.utils          [428]: ERROR   764c0bd8 -- stderr: '  File "/config/fail2ban/Fail2Ban.py", line 98, in <module>'
2020-05-15 10:03:42,267 fail2ban.utils          [428]: ERROR   764c0bd8 -- stderr: '    if (payload:= disc.create_payload()):'
2020-05-15 10:03:42,267 fail2ban.utils          [428]: ERROR   764c0bd8 -- stderr: '  File "/config/fail2ban/Fail2Ban.py", line 28, in create_payload'
2020-05-15 10:03:42,268 fail2ban.utils          [428]: ERROR   764c0bd8 -- stderr: '    webhook["embeds"][0]["image"] = {"url": f"{self.data[\'map-img\']}"}'
2020-05-15 10:03:42,268 fail2ban.utils          [428]: ERROR   764c0bd8 -- stderr: "KeyError: 'map-img'"
2020-05-15 10:03:42,269 fail2ban.utils          [428]: ERROR   764c0bd8 -- returned 1
2020-05-15 10:03:42,269 fail2ban.actions        [428]: ERROR   Failed to execute ban jail 'nginx-http-auth' action 'discordEmbed' info 'ActionInfo({'ip': '172.247.109.34', 'fid': <function Actions.ActionInfo.<lambda> at 0x7684f9b8>, 'failures': 4, 'raw-ticket': <function Actions.ActionInfo.<lambda> at 0x7684fc88>})': Error banning 172.247.109.34
2020-05-15 10:03:42,270 fail2ban.actions        [428]: NOTICE  [nginx-http-auth] Restore Ban 172.247.109.37
2020-05-15 10:03:43,890 fail2ban.utils          [428]: #39-Lev. 764c0db8 -- exec: python3 /config/fail2ban/Fail2Ban.py -a ban -j nginx-botsearch -i 218.80.229.142 -t 24 -f 2
2020-05-15 10:03:43,891 fail2ban.utils          [428]: ERROR   764c0db8 -- stderr: 'Traceback (most recent call last):'
2020-05-15 10:03:43,891 fail2ban.utils          [428]: ERROR   764c0db8 -- stderr: '  File "/config/fail2ban/Fail2Ban.py", line 98, in <module>'
2020-05-15 10:03:43,892 fail2ban.utils          [428]: ERROR   764c0db8 -- stderr: '    if (payload:= disc.create_payload()):'
2020-05-15 10:03:43,892 fail2ban.utils          [428]: ERROR   764c0db8 -- stderr: '  File "/config/fail2ban/Fail2Ban.py", line 28, in create_payload'
2020-05-15 10:03:43,892 fail2ban.utils          [428]: ERROR   764c0db8 -- stderr: '    webhook["embeds"][0]["image"] = {"url": f"{self.data[\'map-img\']}"}'
2020-05-15 10:03:43,893 fail2ban.utils          [428]: ERROR   764c0db8 -- stderr: "KeyError: 'map-img'"
2020-05-15 10:03:43,893 fail2ban.utils          [428]: ERROR   764c0db8 -- returned 1
2020-05-15 10:03:43,894 fail2ban.actions        [428]: ERROR   Failed to execute ban jail 'nginx-botsearch' action 'discordEmbed' info 'ActionInfo({'ip': '218.80.229.142', 'fid': <function Actions.ActionInfo.<lambda> at 0x7684f9b8>, 'failures': 2, 'raw-ticket': <function Actions.ActionInfo.<lambda> at 0x7684fc88>})': Error banning 218.80.229.142
2020-05-15 10:03:43,895 fail2ban.actions        [428]: NOTICE  [nginx-botsearch] Restore Ban 3.14.255.136
2020-05-15 10:03:45,579 fail2ban.utils          [428]: #39-Lev. 764c0bd8 -- exec: python3 /config/fail2ban/Fail2Ban.py -a ban -j nginx-http-auth -i 172.247.109.37 -t 24 -f 3
2020-05-15 10:03:45,580 fail2ban.utils          [428]: ERROR   764c0bd8 -- stderr: 'Traceback (most recent call last):'
2020-05-15 10:03:45,581 fail2ban.utils          [428]: ERROR   764c0bd8 -- stderr: '  File "/config/fail2ban/Fail2Ban.py", line 98, in <module>'
2020-05-15 10:03:45,581 fail2ban.utils          [428]: ERROR   764c0bd8 -- stderr: '    if (payload:= disc.create_payload()):'
2020-05-15 10:03:45,581 fail2ban.utils          [428]: ERROR   764c0bd8 -- stderr: '  File "/config/fail2ban/Fail2Ban.py", line 28, in create_payload'
2020-05-15 10:03:45,582 fail2ban.utils          [428]: ERROR   764c0bd8 -- stderr: '    webhook["embeds"][0]["image"] = {"url": f"{self.data[\'map-img\']}"}'
2020-05-15 10:03:45,582 fail2ban.utils          [428]: ERROR   764c0bd8 -- stderr: "KeyError: 'map-img'"
2020-05-15 10:03:45,582 fail2ban.utils          [428]: ERROR   764c0bd8 -- returned 1
2020-05-15 10:03:45,583 fail2ban.actions        [428]: ERROR   Failed to execute ban jail 'nginx-http-auth' action 'discordEmbed' info 'ActionInfo({'ip': '172.247.109.37', 'fid': <function Actions.ActionInfo.<lambda> at 0x7684f9b8>, 'failures': 3, 'raw-ticket': <function Actions.ActionInfo.<lambda> at 0x7684fc88>})': Error banning 172.247.109.37
2020-05-15 10:03:45,584 fail2ban.actions        [428]: NOTICE  [nginx-http-auth] Restore Ban 172.247.109.52
2020-05-15 10:03:47,208 fail2ban.utils          [428]: #39-Lev. 764c0db8 -- exec: python3 /config/fail2ban/Fail2Ban.py -a ban -j nginx-botsearch -i 3.14.255.136 -t 24 -f 2
2020-05-15 10:03:47,209 fail2ban.utils          [428]: ERROR   764c0db8 -- stderr: 'Traceback (most recent call last):'
2020-05-15 10:03:47,209 fail2ban.utils          [428]: ERROR   764c0db8 -- stderr: '  File "/config/fail2ban/Fail2Ban.py", line 98, in <module>'
2020-05-15 10:03:47,210 fail2ban.utils          [428]: ERROR   764c0db8 -- stderr: '    if (payload:= disc.create_payload()):'
2020-05-15 10:03:47,210 fail2ban.utils          [428]: ERROR   764c0db8 -- stderr: '  File "/config/fail2ban/Fail2Ban.py", line 28, in create_payload'
2020-05-15 10:03:47,210 fail2ban.utils          [428]: ERROR   764c0db8 -- stderr: '    webhook["embeds"][0]["image"] = {"url": f"{self.data[\'map-img\']}"}'
2020-05-15 10:03:47,211 fail2ban.utils          [428]: ERROR   764c0db8 -- stderr: "KeyError: 'map-img'"
2020-05-15 10:03:47,211 fail2ban.utils          [428]: ERROR   764c0db8 -- returned 1
2020-05-15 10:03:47,212 fail2ban.actions        [428]: ERROR   Failed to execute ban jail 'nginx-botsearch' action 'discordEmbed' info 'ActionInfo({'ip': '3.14.255.136', 'fid': <function Actions.ActionInfo.<lambda> at 0x7684f9b8>, 'failures': 2, 'raw-ticket': <function Actions.ActionInfo.<lambda> at 0x7684fc88>})': Error banning 3.14.255.136
2020-05-15 10:03:47,213 fail2ban.actions        [428]: NOTICE  [nginx-botsearch] Restore Ban 34.87.75.93
```

**Comment by Roxedus** [comment]
Thanks. I was kind of aware of this issue. I did a rewrite of the file to account for it, with some other bugs.

You can test it out with either updating your action, or by overwrite the current file with the dev version.

```bash
docker exec letsencrypt cp /AwesomeFolder/Fail2Ban-dev.py /config/fail2ban/Fail2Ban.py
docker exec letsencrypt chmod +x /config/fail2ban/Fail2Ban.py
```

**Comment by M203** [comment]
Ok, I ran the above commands. But I feel I have might have missed something. Fail2ban log says as follows. Note, it fails to start the jails, non-dev version starting jails worked and produced discord notification. 

```
2020-05-16 10:23:22,828 fail2ban.jail           [418]: INFO    Jail 'nginx-http-auth' started
2020-05-16 10:23:22,862 fail2ban.jail           [418]: INFO    Jail 'nginx-botsearch' started
2020-05-16 10:23:22,867 fail2ban.jail           [418]: INFO    Jail 'nginx-badbots' started
2020-05-16 10:23:26,926 fail2ban.utils          [418]: #39-Lev. 7663a320 -- exec: python3 /config/fail2ban/Fail2Ban.py -a start -j nginx-http-auth
2020-05-16 10:23:26,927 fail2ban.utils          [418]: ERROR   7663a320 -- stderr: 'Traceback (most recent call last):'
2020-05-16 10:23:26,927 fail2ban.utils          [418]: ERROR   7663a320 -- stderr: '  File "/config/fail2ban/Fail2Ban.py", line 211, in <module>'
2020-05-16 10:23:26,927 fail2ban.utils          [418]: ERROR   7663a320 -- stderr: '    if (payload:= disc.create_payload()):'
2020-05-16 10:23:26,928 fail2ban.utils          [418]: ERROR   7663a320 -- stderr: '  File "/config/fail2ban/Fail2Ban.py", line 78, in create_payload'
2020-05-16 10:23:26,928 fail2ban.utils          [418]: ERROR   7663a320 -- stderr: '    if isinstance(str, self.user):'
2020-05-16 10:23:26,928 fail2ban.utils          [418]: ERROR   7663a320 -- stderr: 'TypeError: isinstance() arg 2 must be a type or tuple of types'
2020-05-16 10:23:26,928 fail2ban.utils          [418]: ERROR   7663a320 -- returned 1
2020-05-16 10:23:26,929 fail2ban.actions        [418]: ERROR   Failed to start jail 'nginx-http-auth' action 'discordEmbed': Error starting action Jail('nginx-http-auth')/discordEmbed
2020-05-16 10:23:26,930 fail2ban.actions        [418]: NOTICE  [nginx-http-auth] Restore Ban 101.2.163.49
2020-05-16 10:23:29,855 fail2ban.utils          [418]: #39-Lev. 7663a500 -- exec: python3 /config/fail2ban/Fail2Ban.py -a start -j nginx-botsearch
2020-05-16 10:23:29,856 fail2ban.utils          [418]: ERROR   7663a500 -- stderr: 'Traceback (most recent call last):'
2020-05-16 10:23:29,856 fail2ban.utils          [418]: ERROR   7663a500 -- stderr: '  File "/config/fail2ban/Fail2Ban.py", line 211, in <module>'
2020-05-16 10:23:29,856 fail2ban.utils          [418]: ERROR   7663a500 -- stderr: '    if (payload:= disc.create_payload()):'
2020-05-16 10:23:29,856 fail2ban.utils          [418]: ERROR   7663a500 -- stderr: '  File "/config/fail2ban/Fail2Ban.py", line 78, in create_payload'
2020-05-16 10:23:29,857 fail2ban.utils          [418]: ERROR   7663a500 -- stderr: '    if isinstance(str, self.user):'
2020-05-16 10:23:29,857 fail2ban.utils          [418]: ERROR   7663a500 -- stderr: 'TypeError: isinstance() arg 2 must be a type or tuple of types'
2020-05-16 10:23:29,857 fail2ban.utils          [418]: ERROR   7663a500 -- returned 1
2020-05-16 10:23:29,859 fail2ban.actions        [418]: ERROR   Failed to start jail 'nginx-botsearch' action 'discordEmbed': Error starting action Jail('nginx-botsearch')/discordEmbed
2020-05-16 10:23:29,864 fail2ban.actions        [418]: NOTICE  [nginx-botsearch] Restore Ban 1.203.191.242
2020-05-16 10:23:32,849 fail2ban.utils          [418]: #39-Lev. 76319c80 -- exec: python3 /config/fail2ban/Fail2Ban.py -a start -j nginx-badbots
2020-05-16 10:23:32,850 fail2ban.utils          [418]: ERROR   76319c80 -- stderr: 'Traceback (most recent call last):'
2020-05-16 10:23:32,851 fail2ban.utils          [418]: ERROR   76319c80 -- stderr: '  File "/config/fail2ban/Fail2Ban.py", line 211, in <module>'
2020-05-16 10:23:32,851 fail2ban.utils          [418]: ERROR   76319c80 -- stderr: '    if (payload:= disc.create_payload()):'
2020-05-16 10:23:32,851 fail2ban.utils          [418]: ERROR   76319c80 -- stderr: '  File "/config/fail2ban/Fail2Ban.py", line 78, in create_payload'
2020-05-16 10:23:32,852 fail2ban.utils          [418]: ERROR   76319c80 -- stderr: '    if isinstance(str, self.user):'
2020-05-16 10:23:32,852 fail2ban.utils          [418]: ERROR   76319c80 -- stderr: 'TypeError: isinstance() arg 2 must be a type or tuple of types'
2020-05-16 10:23:32,852 fail2ban.utils          [418]: ERROR   76319c80 -- returned 1
2020-05-16 10:23:32,853 fail2ban.actions        [418]: ERROR   Failed to start jail 'nginx-badbots' action 'discordEmbed': Error starting action Jail('nginx-badbots')/discordEmbed
2020-05-16 10:23:36,068 fail2ban.utils          [418]: #39-Lev. 7677cd40 -- exec: python3 /config/fail2ban/Fail2Ban.py -a ban -j nginx-http-auth -i 101.2.163.49 -t 24 -f 3
2020-05-16 10:23:36,069 fail2ban.utils          [418]: ERROR   7677cd40 -- stderr: 'Traceback (most recent call last):'
2020-05-16 10:23:36,069 fail2ban.utils          [418]: ERROR   7677cd40 -- stderr: '  File "/config/fail2ban/Fail2Ban.py", line 211, in <module>'
2020-05-16 10:23:36,070 fail2ban.utils          [418]: ERROR   7677cd40 -- stderr: '    if (payload:= disc.create_payload()):'
2020-05-16 10:23:36,070 fail2ban.utils          [418]: ERROR   7677cd40 -- stderr: '  File "/config/fail2ban/Fail2Ban.py", line 78, in create_payload'
2020-05-16 10:23:36,070 fail2ban.utils          [418]: ERROR   7677cd40 -- stderr: '    if isinstance(str, self.user):'
2020-05-16 10:23:36,071 fail2ban.utils          [418]: ERROR   7677cd40 -- stderr: 'TypeError: isinstance() arg 2 must be a type or tuple of types'
2020-05-16 10:23:36,071 fail2ban.utils          [418]: ERROR   7677cd40 -- returned 1
2020-05-16 10:23:36,072 fail2ban.actions        [418]: ERROR   Failed to execute ban jail 'nginx-http-auth' action 'discordEmbed' info 'ActionInfo({'ip': '101.2.163.49', 'fid': <function Actions.ActionInfo.<lambda> at 0x76769970>, 'failures': 3, 'raw-ticket': <function Actions.ActionInfo.<lambda> at 0x76769c40>})': Error banning 101.2.163.49
2020-05-16 10:23:36,073 fail2ban.actions        [418]: NOTICE  [nginx-http-auth] Restore Ban 103.1.209.128
2020-05-16 10:23:39,372 fail2ban.utils          [418]: #39-Lev. 7677cf20 -- exec: python3 /config/fail2ban/Fail2Ban.py -a ban -j nginx-botsearch -i 1.203.191.242 -t 24 -f 2
2020-05-16 10:23:39,373 fail2ban.utils          [418]: ERROR   7677cf20 -- stderr: 'Traceback (most recent call last):'
2020-05-16 10:23:39,373 fail2ban.utils          [418]: ERROR   7677cf20 -- stderr: '  File "/config/fail2ban/Fail2Ban.py", line 211, in <module>'
2020-05-16 10:23:39,374 fail2ban.utils          [418]: ERROR   7677cf20 -- stderr: '    if (payload:= disc.create_payload()):'
2020-05-16 10:23:39,374 fail2ban.utils          [418]: ERROR   7677cf20 -- stderr: '  File "/config/fail2ban/Fail2Ban.py", line 78, in create_payload'
2020-05-16 10:23:39,374 fail2ban.utils          [418]: ERROR   7677cf20 -- stderr: '    if isinstance(str, self.user):'
2020-05-16 10:23:39,375 fail2ban.utils          [418]: ERROR   7677cf20 -- stderr: 'TypeError: isinstance() arg 2 must be a type or tuple of types'
2020-05-16 10:23:39,375 fail2ban.utils          [418]: ERROR   7677cf20 -- returned 1
2020-05-16 10:23:39,375 fail2ban.actions        [418]: ERROR   Failed to execute ban jail 'nginx-botsearch' action 'discordEmbed' info 'ActionInfo({'ip': '1.203.191.242', 'fid': <function Actions.ActionInfo.<lambda> at 0x76769970>, 'failures': 2, 'raw-ticket': <function Actions.ActionInfo.<lambda> at 0x76769c40>})': Error banning 1.203.191.242
2020-05-16 10:23:39,376 fail2ban.actions        [418]: NOTICE  [nginx-botsearch] Restore Ban 1.232.152.86
2020-05-16 10:23:42,632 fail2ban.utils          [418]: #39-Lev. 7677cd40 -- exec: python3 /config/fail2ban/Fail2Ban.py -a ban -j nginx-http-auth -i 103.1.209.128 -t 24 -f 3
2020-05-16 10:23:42,633 fail2ban.utils          [418]: ERROR   7677cd40 -- stderr: 'Traceback (most recent call last):'
2020-05-16 10:23:42,633 fail2ban.utils          [418]: ERROR   7677cd40 -- stderr: '  File "/config/fail2ban/Fail2Ban.py", line 211, in <module>'
2020-05-16 10:23:42,633 fail2ban.utils          [418]: ERROR   7677cd40 -- stderr: '    if (payload:= disc.create_payload()):'
2020-05-16 10:23:42,634 fail2ban.utils          [418]: ERROR   7677cd40 -- stderr: '  File "/config/fail2ban/Fail2Ban.py", line 78, in create_payload'
2020-05-16 10:23:42,634 fail2ban.utils          [418]: ERROR   7677cd40 -- stderr: '    if isinstance(str, self.user):'
2020-05-16 10:23:42,634 fail2ban.utils          [418]: ERROR   7677cd40 -- stderr: 'TypeError: isinstance() arg 2 must be a type or tuple of types'
2020-05-16 10:23:42,635 fail2ban.utils          [418]: ERROR   7677cd40 -- returned 1
```

**Comment by Roxedus** [comment]
I thought I pushed that fix. But apparently i did not. It is now though

**Comment by M203** [comment]
Thanks! Works great now! Really cool!

**Comment by Roxedus** [comment]
So that fixed it?
